services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/image_processor
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=image_processor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: bash -c "cd /app && celery -A src.core.tasks worker --loglevel=info"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/image_processor
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: celery -A src.core.tasks flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
  redis_data: 